services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: joidb
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db

  # server:
  #   build:
  #     context: ./server
  #   depends_on:
  #     - mongo
  #   restart: always

  # sensor:
  #   build:
  #     context: ./sensor
  #   depends_on:
  #     - mongo
  #   restart: always

  # bridge:
  #   build:
  #     context: ./bridge
  #   depends_on:
  #     - mongo
  #   restart: always

volumes:
  mongodata:
